name: Lint/Publish Ansible Collection

on:
  push:
    branches: [main]
    paths: ["ansible_collection/**"]
    tags: ["ansible-v*"]
  pull_request:
    paths: ["ansible_collection/**"]
  workflow_dispatch:

env:
  COLLECTION_PATH: ansible_collection

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v25.1.2
        with:
          working_directory: ${{ env.COLLECTION_PATH }}

  publish:
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ansible-v')
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-publish-action@v1.0.0
        with:
          src_path: ${{ env.COLLECTION_PATH }}
          api_key: ${{ secrets.GALAXY_API_KEY }}
