name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push'
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bws-cache

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4


    # Disabled since the ARM64 builds take a ridiculous amount of time.
    # - uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=pr

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push != 'false' }} # is null if trigger != workflow_dispatch
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        # Disabled since the ARM64 builds take a ridiculous amount of time.
        # platforms: linux/amd64,linux/arm64
        # Build cache is scoped to branches by default.
        # We use the main branch as a fallback if there's no cache for the existing branch.
        # https://stackoverflow.com/a/77127188/5209106
        cache-from: |
          type=gha
          type=gha,scope=main
        cache-to: type=gha,mode=max
        provenance: false
